# Disable in-IDE auth; Gen3 (WTS + Ambassador) terminates auth
auth-none=1
www-address=0.0.0.0
www-port=8787
server-user=rstudio
www-frame-origin=same
# Help rsession find R explicitly
rsession-which-r=/usr/local/bin/R
rsession-ld-library-path=/usr/local/lib/R/lib